config/routes.rb
Rails.application.routes.draw do

  #=== Root routes ===#

  root to: 'visitors#index'

  get 'signin' => 'users#signin'

  post 'do_signin' => 'users#do_signin'

  get 'signout' => 'users#signout'

  post 'check_user' => 'users#check_user'

  get 'signup' => 'users#signup'
  post 'do_signup' => 'users#do_signup'

  post 'check_email' => 'users#check_email'

  get 'profile' => 'visitors#profile'

  get 'create' => 'users#create'

  #make this your last route.
  # get '*unmatched_route', :to => 'application#raise_not_found!'

  # unless Rails.application.config.consider_all_requests_local
  #   get '*not_found', to: 'visitors#redirect', :format => false
  # end

end

app/models/user.rb
require 'users_helper'
require 'user_mailer'

class User < ActiveRecord::Base

  # belongs_to :referrer, class_name: 'User', foreign_key: 'referrer_id'
  # has_many :referrals, class_name: 'User', foreign_key: 'referrer_id'

  def find_by_sql(sql, binds = [])
    connection.select_all(sanitize_sql(sql), "#{name} Load", binds).collect! { |record| instantiate(record) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

#  before_filter :ref_to_session

  #called by last route matching unmatched routes.  Raises RoutingError which will be rescued from in the same way as other exceptions.
  def raise_not_found!
    # render 'visitors/404'
    render :file => 'public/404.html', :status => :not_found, :layout => false
  end

end

app/controllers/users_controller.rb
require 'digest/md5'

class UsersController < ApplicationController
  # before_filter :skip_first_page, only: :index

  def signup
      @title = 'User | Sign Up'
      if session[:user_email]
        @user = User.find_by_email(session[:user_email])
      end

  end

  def create
      @title = 'User | Create'
      cookies[:create_new] = 1;
      @user = User.find_by_email(session[:user_email])
      render 'users/signup'

  end

  def do_signup
    @user = User.new(user_params)
    @user.password = Digest::MD5.hexdigest(params[:password])

    if @user.save
      flash[:notice_type]    = 'success'
      flash[:notice_content] = 'Account has registered successfully.'
    else
      flash[:notice_type]    = 'danger'
      flash[:notice_content]  = 'Something went wrong!'
      redirect_to root_path
    end

    if cookies[:create_new] != 1
      session[:user_email] = @user.email
      cookies[:create_new] = 0
    end
    redirect_to root_path

  end

  def signin
    if session[:user_email]
      redirect_to root_path
    else
      @title = 'User | Sign In'
    end
  end

  def do_signin
    email = params[:email]
    password = Digest::MD5.hexdigest(params[:password])
    location = params[:location]
    @user = User.where(:email => email, :password => password, :location => location).first
    if @user.nil?
      flash[:notice_type]    = 'danger'
      flash[:notice_content]  = 'Invalid email or password'

      redirect_to root_path
    else
      flash[:notice_type]    = 'success'
      flash[:notice_content]  = 'You are now signed in.'

      session[:user_email] = @user.email
      cookies[:create_new] = 0
      redirect_to root_path
    end
  end

  def signout
    session.delete(:user_email)

    flash[:notice_type]    = 'success'
    flash[:notice_content]  = 'You are now signed out.'
    redirect_to root_path
  end

  def check_user
    email = params[:email]
    password = Digest::MD5.hexdigest(params[:password])
    location = params[:location]
    @user = User.where(:email => email, :password => password, :location => location).first
    if @user.nil?
      @user = User.new
      @user.email = 'null'
    end
    render json: @user
  end

  def check_email
    email = params[:email]
    @user = User.find_by_email(email)
    if @user.nil?
      @user = User.new
      @user.email = 'null'
    end
    render json: @user
  end

  def user_params
    params.permit(:email, :name, :phone, :location, :party_size)
  end


end

app/controllers/visitors_controller.rb
require 'digest/md5'

class VisitorsController < ApplicationController
  before_filter :check_session

  def check_session
    if !session[:user_email]
      redirect_to signin_path
    end
  end

  def index
      @title = 'User | Table'
      cookies[:create_new] = 0;
      @user = User.find_by_email(session[:user_email])
      @user_list = User.all
  end

  def profile
      @title = 'User | Profile'
      @user = User.find_by_email(session[:user_email])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="page-footer-inner">
    2014 &copy; Metronic by keenthemes.
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="page-header navbar navbar-fixed-top">
  <div class="page-header-inner">
    <div class="page-logo">
      <a href="#">
        <img src="/assets/logo.png" alt="logo" class="logo-default"/>
      </a>
    </div>
    <div class="top-menu">
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown dropdown-user">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class="username"> <i class="fa fa-user"></i> </span>
            <span class="username"> <%= @user.name %> </span>
            <i class="fa fa-angle-down"></i>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="<%= profile_path %>">
                <i class="fa fa-gear"></i> My Profile </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="<%= signout_path %>">
                <i class="fa fa-sign-out"></i> Log Out </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="clearfix">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="" name="description"/>
  <meta content="" name="author"/>

  <title><%= @title %></title>

  <!-- Include the CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag controller_name if Rails.application.assets.find_asset("#{controller_name}.css") %>
  <%= csrf_meta_tags %>

  <link rel="icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">
  <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">

</head>

<% if session[:user_email] && cookies[:create_new] == 0 %>
  <%= render 'layouts/header' %>
<% end %>

<%= yield %>

<!-- Include jQuery (required) and the JS -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag controller_name if Rails.application.assets.find_asset("#{controller_name}.js") %>

<% if session[:user_email] && cookies[:create_new] == 0 %>
  <%= render 'layouts/footer' %>
<% end %>

</body>
</html>

app/views/users/signin.html.erb
<body class="login">

<div class="logo">
  <a href="#">
    <img src="/assets/logo-big.png" alt=""/>
  </a>
</div>
<div class="content">
  <form class="login-form" action="<%= do_signin_path %>" method="post">
    <h3 class="form-title">Login to your account</h3>
    <div class="alert alert-danger display-hide" id="signin_alert">
      <button class="close" data-close="alert"></button>
			<span>
			Enter any email, password and location. </span>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Email</label>
      <div class="input-icon">
        <i class="fa fa-envelope"></i>
        <input class="form-control placeholder-no-fix" type="email" autocomplete="off" placeholder="Email" id="signin_email" name="email"/>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Password</label>
      <div class="input-icon">
        <i class="fa fa-lock"></i>
        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" id="signin_password" name="password"/>
      </div>
    </div>
    <div class="form-group">
      <div class="input-icon">
        <i class="fa fa-map-marker"></i>
        <select class="form-control placeholder-no-fix" name="location" id="signin_location" style="padding-left: 25px;">
          <option value=""> Location</option>
          <option value="Loc1"> Loc1</option>
          <option value="Loc2"> Loc2</option>
          <option value="Loc3"> Loc3</option>
        </select>
      </div>
    </div>
    <div class="form-actions">
      <button type="button" id="signin_button" class="btn blue pull-right">
        Sign In <i class="m-icon-swapright m-icon-white"></i>
      </button>
    </div>
    <div class="create-account">
      <p>
        Don't have an account yet ?&nbsp; <a href="<%= signup_path %>">
        Create an account </a>
      </p>
    </div>
  </form>

</div>

<div class="copyright">
  2014 &copy; Metronic - Admin Dashboard Template.
</div>

app/views/users/signup.html.erb
<body class="login">

<div class="logo">
  <a href="#">
    <img src="/assets/logo-big.png" alt=""/>
  </a>
</div>
<div class="content">
  <form class="register-form" action="<%= do_signup_path %>" method="post">
    <h3>Sign Up</h3>
    <p>
      Enter your personal details below:
    </p>
    <div class="alert alert-danger display-hide" id="signup_alert">
      <button class="close" data-close="alert"></button>
			<span>
			This email has already registered. </span>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Name</label>
      <div class="input-icon">
        <i class="fa fa-font"></i>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Name" name="name"/>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Email</label>
      <div class="input-icon">
        <i class="fa fa-envelope"></i>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Email" id="signup_email" name="email"/>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Phone</label>
      <div class="input-icon">
        <i class="fa fa-phone"></i>
        <input class="form-control placeholder-no-fix" type="text" placeholder="Phone Number" name="phone"/>
      </div>
    </div>
    <div class="form-group">
      <div class="input-icon">
        <i class="fa fa-map-marker"></i>
        <select class="form-control placeholder-no-fix" name="location" style="padding-left: 25px;">
          <option value=""> Location</option>
          <option value="Loc1"> Loc1</option>
          <option value="Loc2"> Loc2</option>
          <option value="Loc3"> Loc3</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="input-icon">
        <i class="fa fa-tags"></i>
        <select class="form-control placeholder-no-fix" name="party_size" style="padding-left: 25px;">
          <option value=""> Party Size</option>
          <option value="1"> 1</option>
          <option value="2"> 2</option>
          <option value="3"> 3</option>
          <option value="3"> 4</option>
          <option value="3"> 5</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Password</label>
      <div class="input-icon">
        <i class="fa fa-lock"></i>
        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="password"/>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
      <div class="controls">
        <div class="input-icon">
          <i class="fa fa-check"></i>
          <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="rpassword"/>
        </div>
      </div>
    </div>
    <div class="form-actions">
      <a href="<%= root_path %>" class="btn">
        <i class="m-icon-swapleft"></i> Back </a>
      <button type="button" id="signup_button" class="btn blue pull-right">
        Sign Up <i class="m-icon-swapright m-icon-white"></i>
      </button>
    </div>
  </form>
</div>

<div class="copyright">
  2014 &copy; Metronic - Admin Dashboard Template.
</div>

app/views/visitors/index.html.erb
<body class="page-header-fixed page-quick-sidebar-over-content ">

<!-- Notification Message -->
<% if flash[:notice_content] %>
    <div class="alert alert-<%= flash[:notice_type] %> alert-dismissible" role="alert" style="margin-bottom: 0px;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong><%= flash[:notice_content] %></strong>
    </div>
<% end %>
<!-- // ENd Notification Message -->

<div class="page-container">
  <div class="page-content">
    <div class="row">
      <div class="page-title" style="float: right; margin-right: 50px;">
        <a href="<%= create_path %>" class="btn blue"> <i class="fa fa-plus-circle"></i> &nbsp; Create New </a>
      </div>
      <div class="col-md-12">
        <div class="portlet box blue-hoki">
          <div class="portlet-title">
            <div class="caption">
              <i class="fa fa-users"></i> User List Table
            </div>
            <div class="tools">
            </div>
          </div>
          <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" id="sample_1">
              <thead>
              <tr>
                <th> Name </th>
                <th> Email </th>
                <th> Phone Number </th>
                <th> Location </th>
                <th> Party Size </th>
              </tr>
              </thead>
              <tbody>
              <% @user_list.each do |userItem| %>
              <tr>
                <td> <%= userItem.name %> </td>
                <td> <%= userItem.email %> </td>
                <td> <%= userItem.phone %> </td>
                <td> <%= userItem.location %> </td>
                <td> <%= userItem.party_size %> </td>
              </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/visitors/profile.html.erb
<body class="page-header-fixed page-quick-sidebar-over-content ">

<!-- Notification Message -->
<% if flash[:notice_content] %>
    <div class="alert alert-<%= flash[:notice_type] %> alert-dismissible" role="alert" style="margin-bottom: 0px;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong><%= flash[:notice_content] %></strong>
    </div>
<% end %>
<!-- // ENd Notification Message -->

<div class="page-container">
  <div class="page-content">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <form role="form" action="#">
          <div class="form-group">
            <h3>Profile Page</h3>
          </div>
          <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" placeholder="John Doe" class="form-control" value="<%= @user.name %>"/>
          </div>
          <div class="form-group">
            <label class="control-label">Email</label>
            <input type="email" placeholder="user@gmail.com" class="form-control" value="<%= @user.email %>"/>
          </div>
          <div class="form-group">
            <label class="control-label">Phone Number</label>
            <input type="text" placeholder="+1234567890 DEMO" class="form-control" value="<%= @user.phone %>"/>          </div>
          <div class="form-group">
            <label class="control-label">Location</label>
            <input type="text" placeholder="Location Area" class="form-control" value="<%= @user.location %>"/>
          </div>
          <div class="form-group">
            <label class="control-label">Party Size</label>
            <input type="text" placeholder="Party Size" class="form-control" value="<%= @user.party_size %>"/>
          </div>
          <div class="form-group">
            <label class="control-label">New Password</label>
            <input type="password" placeholder="Type New Password" class="form-control"/>
          </div>
          <div class="form-group">
            <label class="control-label">Confirm Password</label>
            <input type="password" placeholder="Retype Password" class="form-control"/>
          </div>

          <div class="margiv-top-10">
            <a href="#" class="btn green">
              <i class="fa fa-save"></i> Update Profile </a>
            <a href="<%= root_path %>" class="btn default">
              <i class="fa fa-arrow-circle-o-left"></i> Cancel </a>
          </div>
          <div class="form-group">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>